### ISSUE TITLE
[Bug] Fresh npm install does not work

### ISSUE THREAD

**Issue by piotrpoz** [creativetimofficial/ct-now-ui-kit-pro-react#5]
### Version
1.5.0
### Reproduction link
Fresh install, nothing to share
### Operating System
Ubuntu
### Device
mac
### Browser & Version
It didn't go that far...
### Steps to reproduce
In the documentation it says to extract zip file and run npm install command. 
I am running npm install.
### What is expected?
Node modules should be installed.
### What is actually happening?
npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: now-ui-kit-pro-react@1.5.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0" from react-datetime@3.0.4
npm ERR! node_modules/react-datetime
npm ERR!   react-datetime@"3.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-07T16_50_02_196Z-debug.log

---
### Solution
I don't have any.
### Additional comments
I suggest test prod build on a machine that wasn't previously used for development purposes.

**Comment by edbitio** [comment]
Has anyone resolved this problem? I am running into the same issue.

**Comment by sajadevo** [comment]
**Hi @piotrpoz & @edbitio**

We've updated the product and the is fixed now.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by karthikraja95** [comment]
I Still get this error. Dependency Issues. Could you please change the package.json to working dependencies?

<img width="553" alt="Screen Shot 2022-08-11 at 1 12 00 PM" src="https://user-images.githubusercontent.com/40802179/184193626-49e52bc5-8c3c-4923-a97a-d2bbfdae83c3.png">

**Comment by sajadevo** [comment]
> 

On the package.json place replace the following:

```
"peerDependencies": {
    "react": ">=16.8.0",
    "react-dom": ">=16.8.0"
  },
```

With

```
"peerDependencies": {
    "react": ">=16.0.0",
    "react-dom": ">=16.0.0"
  },
```

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
